package com.google.android.overlay.devicelockcontroller;
/* JADX INFO: This class is generated by JADX */
public final class R {

    public static final class array {
        public static final int lock_task_allowlist = 0x7f010000;
    }

    public static final class integer {
        public static final int check_in_server_port_number = 0x7f020000;
    }

    public static final class string {
        public static final int check_in_server_host_name = 0x7f030000;
    }
}
